obstacle_range: 2.5
raytrace_range: 10.0

footprint: [[0.45,0.35],[0.45,-0.35],[-0.45,-0.35],[-0.45,0.35]]
#robot_radius: ir_of_robot
inflation_radius: 0.25

observation_sources: point_cloud_sensor laser_scan_sensor

point_cloud_sensor: {sensor_frame: realsense_optical_link, data_type: PointCloud2, topic: /realsense/depth/points , marking: true, clearing: true, min_obstacle_height: 0.1}

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}