DWAPlannerROS:
 max_vel_x: 0.75
 min_vel_x: 0.1
 max_vel_y: 0
 min_vel_y: 0
 max_rot_vel: 1.5
 min_rot_vel: 0.2
 max_trans_vel: 0.4
 min_trans_vel: 0.1
 acc_lim_th: 3.2
 acc_lim_x: 2.5
 acc_lim_y: 0
 yaw_goal_tolerance: 0.1
 xy_goal_tolerance: 0.2

 holonomic_robot: true
